Ruby_Scripts/notificator/config/routes.rb
Rails.application.routes.draw do
  root to: 'notifications#index'

  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Websockets resemble this URL
  mount ActionCable.server => '/cable'
end

Ruby_Scripts/notificator/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Ruby_Scripts/notificator/app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { notify }

  private

  def notify
    Notification.create(event: "New Notification (#{self.body})")
  end
end

Ruby_Scripts/notificator/app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit { NotificationBroadcastJob.perform_later(Notification.count,self)}
end

Ruby_Scripts/notificator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Ruby_Scripts/notificator/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body)
    end
end

Ruby_Scripts/notificator/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.all.reverse
  end
end

Ruby_Scripts/notificator/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby_Scripts/notificator/app/helpers/messages_helper.rb
module MessagesHelper
end

Ruby_Scripts/notificator/app/helpers/notifications_helper.rb
module NotificationsHelper
end

Ruby_Scripts/notificator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notificator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Ruby_Scripts/notificator/app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby_Scripts/notificator/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

Ruby_Scripts/notificator/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

Ruby_Scripts/notificator/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

Ruby_Scripts/notificator/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

Ruby_Scripts/notificator/app/views/notifications/_counter.html.erb
<li>
  <%= image_tag("icons/notification_bell") %>
  <span  id="notification-counter"><%= counter %></span>
</li>

Ruby_Scripts/notificator/app/views/notifications/_notification.html.erb
<li>
  <%= notification.event %>
  <span> <%= notification.created_at.strftime("%d %b. %Y") %></span>
</li>

Ruby_Scripts/notificator/app/views/notifications/_notification_center.html.erb
<ul class="notificator">
  <a href="#" id="open_notification">
    <%= render 'counter', counter: notifications.count %>
  </a>
  <div id="notificationContainer">
    <div id="notificationTitle">Notifications</div>
    <div id="notificationsBody" class="notifications">
      <ul id="notificationList">
        <%= render notifications %>
      </ul>
    </div>
    <div id="notificationFooter"></div>
  </div>
</ul>

Ruby_Scripts/notificator/app/views/notifications/index.html.erb
<%= render "notification_center", notifications: @notifications %>